name: Release UrhoMatti static website

env:
  APP_LOCATION: "/" # location of client code
  API_LOCATION: "" # location of api source code - optional
  OUTPUT_LOCATION: "build" # location of client code build output

on:
  #push:
  #  branches:
  #  - master
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: npm ci
    - run: npm run build
    
    - name: Build And Deploy
      uses: Azure/static-web-apps-deploy@1a947af9992250f3bc2e68ad0754c0b0c11566c9
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        action: "upload"
        app_location: "/"
        api_location: ""
        output_location: "build"